# -*- coding: utf-8 -*-
"""Lab7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh5Ou5FWzWHcnMt-oZwLi5H80t4XaFiW
"""

import sys
!{sys.executable} -m pip install gmdhpy

import sys
!{sys.executable} -m pip show gmdhpy
from gmdhpy.gmdh import MultilayerGMDH, RefFunctionType
print("OK!")

import sys
!{sys.executable} -m pip install gplearn -q

# ── Ячейка 2: Импорты ─────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import MinMaxScaler

print("Импорты ОК")

# ── Ячейка 3: Загрузка датасета ───────────────────────────────
url = ("https://raw.githubusercontent.com/jbrownlee/Datasets/"
       "master/airline-passengers.csv")
df = pd.read_csv(url, header=0,
                 names=['Month', 'Passengers'], skiprows=1)
df.index = pd.date_range(start='1949-01', periods=len(df), freq='MS')
df = df.drop(columns=['Month'])
series = df['Passengers'].astype(float)

print("=== Первые строки ===")
print(df.head(8))
print(f"\nРазмер: {df.shape}")
print(f"Период: {df.index[0].date()} → {df.index[-1].date()}")
print(f"\nОписательная статистика:\n{series.describe()}")

# ── Ячейка 4: Визуализация ────────────────────────────────────
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

fig, axes = plt.subplots(2, 2, figsize=(14, 9))
fig.suptitle('AirPassengers — анализ временного ряда',
             fontsize=14, fontweight='bold')

# Временной ряд
axes[0, 0].plot(series.index, series.values,
                color='steelblue', linewidth=1.5)
axes[0, 0].set_title('Временной ряд')
axes[0, 0].set_ylabel('Пассажиры (тыс.)')
axes[0, 0].xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

# Скользящее среднее
roll_mean = series.rolling(window=12).mean()
roll_std  = series.rolling(window=12).std()
axes[0, 1].plot(series, label='Исходный', alpha=0.5, color='steelblue')
axes[0, 1].plot(roll_mean, label='MA(12)', color='red')
axes[0, 1].plot(roll_std,  label='STD(12)', color='green')
axes[0, 1].set_title('Скользящее среднее и стандартное отклонение')
axes[0, 1].legend(fontsize=9)

# Тренд
decomp = seasonal_decompose(series, model='multiplicative', period=12)
axes[1, 0].plot(decomp.trend, color='darkorange')
axes[1, 0].set_title('Тренд (мультипликативная декомпозиция)')
axes[1, 0].set_ylabel('Пассажиры')

# Сезонность
axes[1, 1].plot(decomp.seasonal, color='purple')
axes[1, 1].set_title('Сезонность')

plt.tight_layout()
plt.savefig('ts_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

# ACF и PACF
fig, axes = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(series,  lags=40, ax=axes[0], title='ACF')
plot_pacf(series, lags=40, ax=axes[1], title='PACF')
plt.tight_layout()
plt.savefig('acf_pacf.png', dpi=150, bbox_inches='tight')
plt.show()

# ── Ячейка 5: Разделение выборки ──────────────────────────────
TRAIN_SIZE = int(len(series) * 0.8)
train = series.iloc[:TRAIN_SIZE]
test  = series.iloc[TRAIN_SIZE:]

print(f"Обучающая выборка: {len(train)} точек "
      f"({train.index[0].date()} – {train.index[-1].date()})")
print(f"Тестовая выборка:  {len(test)} точек  "
      f"({test.index[0].date()} – {test.index[-1].date()})")

# ── Ячейка 6: МЕТОД 1 — ARIMA ─────────────────────────────────
print("\n" + "="*60)
print("МЕТОД 1: SARIMA(2,1,2)(1,1,1,12)")
print("="*60)

from statsmodels.tsa.arima.model import ARIMA

log_train = np.log(train)

arima_model = ARIMA(log_train, order=(2, 1, 2),
                    seasonal_order=(1, 1, 1, 12))
arima_fit = arima_model.fit()

arima_forecast_log = arima_fit.forecast(steps=len(test))
arima_forecast = np.exp(arima_forecast_log)

mae_arima  = mean_absolute_error(test, arima_forecast)
rmse_arima = np.sqrt(mean_squared_error(test, arima_forecast))
mape_arima = np.mean(np.abs((test.values - arima_forecast.values)
                             / test.values)) * 100

print(f"MAE:  {mae_arima:.2f}")
print(f"RMSE: {rmse_arima:.2f}")
print(f"MAPE: {mape_arima:.2f}%")

# ── Ячейка 7: МЕТОД 2 — Символьная регрессия ──────────────────
print("\n" + "="*60)
print("МЕТОД 2: Символьная регрессия (gplearn)")
print("="*60)

from gplearn.genetic import SymbolicRegressor

MAX_LAG = 12

def make_lag_features(s, lags=12):
    data = {'y': s.values}
    for lag in range(1, lags + 1):
        data[f'lag_{lag}'] = np.roll(s.values, lag)
    df_f = pd.DataFrame(data)
    df_f = df_f.iloc[lags:]
    return df_f['y'].values, df_f.drop(columns='y').values

y_all, X_all = make_lag_features(series, lags=MAX_LAG)
split_idx = TRAIN_SIZE - MAX_LAG

X_train_sr = X_all[:split_idx]
y_train_sr = y_all[:split_idx]
X_test_sr  = X_all[split_idx:]
y_test_sr  = y_all[split_idx:]

sr_model = SymbolicRegressor(
    population_size=500,
    generations=20,
    p_crossover=0.7,
    p_subtree_mutation=0.1,
    p_hoist_mutation=0.05,
    p_point_mutation=0.1,
    max_samples=0.9,
    parsimony_coefficient=0.01,
    random_state=42,
    verbose=1,
    n_jobs=-1
)
sr_model.fit(X_train_sr, y_train_sr)
sr_forecast = sr_model.predict(X_test_sr)

mae_sr  = mean_absolute_error(y_test_sr, sr_forecast)
rmse_sr = np.sqrt(mean_squared_error(y_test_sr, sr_forecast))
mape_sr = np.mean(np.abs((y_test_sr - sr_forecast) / y_test_sr)) * 100

print(f"\nMAE:  {mae_sr:.2f}")
print(f"RMSE: {rmse_sr:.2f}")
print(f"MAPE: {mape_sr:.2f}%")
print(f"\nФормула: {sr_model._program}")

# ── Ячейка 8: Подготовка данных для МГУА ──────────────────────
LAGS = 6

scaler = MinMaxScaler()
series_scaled = scaler.fit_transform(
    series.values.reshape(-1, 1)).flatten()

def make_gmdh_features(s, lags=6):
    X = np.array([s[i - lags:i] for i in range(lags, len(s))])
    y = s[lags:]
    return X, y

X_gmdh, y_gmdh = make_gmdh_features(series_scaled, lags=LAGS)
split_gmdh = int(len(X_gmdh) * 0.8)

X_tr_g = X_gmdh[:split_gmdh]
y_tr_g = y_gmdh[:split_gmdh]
X_te_g = X_gmdh[split_gmdh:]
y_te_g = y_gmdh[split_gmdh:]

y_te_inv = scaler.inverse_transform(
    y_te_g.reshape(-1, 1)).flatten()

print(f"МГУА — обучение: {X_tr_g.shape}, тест: {X_te_g.shape}")

# ── Ячейка 9: МЕТОД 3 — МГУА COMBI (линейный) ─────────────────
print("\n" + "="*60)
print("МЕТОД 3: МГУА — MultilayerGMDH COMBI (линейный)")
print("="*60)

from gmdhpy.gmdh import MultilayerGMDH, RefFunctionType

# COMBI — линейные функции активации
combi = MultilayerGMDH(
    ref_functions=RefFunctionType.rfLinear,
    criterion_type='test_bias',
    seq_type='mode2',
    max_layer_count=5,
    n_jobs=1
)
combi.fit(X_tr_g, y_tr_g)
combi_pred_scaled = combi.predict(X_te_g)
combi_pred = scaler.inverse_transform(
    combi_pred_scaled.reshape(-1, 1)).flatten()

mae_combi  = mean_absolute_error(y_te_inv, combi_pred)
rmse_combi = np.sqrt(mean_squared_error(y_te_inv, combi_pred))
mape_combi = np.mean(np.abs((y_te_inv - combi_pred) / y_te_inv)) * 100

print(f"MAE:  {mae_combi:.2f}")
print(f"RMSE: {rmse_combi:.2f}")
print(f"MAPE: {mape_combi:.2f}%")

# ── Ячейка 10: МЕТОД 4 — МГУА MIA (нелинейный) ────────────────
print("\n" + "="*60)
print("МЕТОД 4: МГУА — MultilayerGMDH MIA (нелинейный)")
print("="*60)

# MIA — нелинейные (квадратичные) функции активации
mia = MultilayerGMDH(
    ref_functions=RefFunctionType.rfQuadratic,
    criterion_type='test_bias',
    seq_type='mode2',
    max_layer_count=5,
    n_jobs=1
)
mia.fit(X_tr_g, y_tr_g)
mia_pred_scaled = mia.predict(X_te_g)
mia_pred = scaler.inverse_transform(
    mia_pred_scaled.reshape(-1, 1)).flatten()

mae_mia  = mean_absolute_error(y_te_inv, mia_pred)
rmse_mia = np.sqrt(mean_squared_error(y_te_inv, mia_pred))
mape_mia = np.mean(np.abs((y_te_inv - mia_pred) / y_te_inv)) * 100

print(f"MAE:  {mae_mia:.2f}")
print(f"RMSE: {rmse_mia:.2f}")
print(f"MAPE: {mape_mia:.2f}%")

# ── Ячейка 11: Визуализация прогнозов ─────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle('Прогнозирование временного ряда AirPassengers',
             fontsize=14, fontweight='bold')

def plot_forecast(ax, title, y_true, pred, color,
                  train_vals=None, train_idx=None, test_idx=None):
    if train_vals is not None:
        ax.plot(train_idx, train_vals,
                color='steelblue', alpha=0.4, label='Обучение')
    ax.plot(test_idx if test_idx is not None else range(len(y_true)),
            y_true, color='steelblue', linewidth=2, label='Факт (тест)')
    n = min(len(y_true), len(pred))
    idx = test_idx[:n] if test_idx is not None else range(n)
    ax.plot(idx, pred[:n], color=color,
            linewidth=2, linestyle='--', label='Прогноз')
    ax.set_title(title, fontweight='bold')
    ax.legend(fontsize=8)
    ax.set_ylabel('Пассажиры')

# ARIMA
plot_forecast(axes[0, 0], 'SARIMA(2,1,2)(1,1,1,12)',
              test.values, arima_forecast.values,
              color='tomato',
              train_vals=train.values,
              train_idx=train.index,
              test_idx=test.index)

# Символьная регрессия
n_sr = min(len(y_test_sr), len(sr_forecast))
plot_forecast(axes[0, 1], 'Символьная регрессия (gplearn)',
              y_test_sr[:n_sr], sr_forecast[:n_sr],
              color='darkorange')

# COMBI
n_g = min(len(y_te_inv), len(combi_pred))
plot_forecast(axes[1, 0], 'МГУА — COMBI (линейный)',
              y_te_inv[:n_g], combi_pred[:n_g],
              color='mediumseagreen')

# MIA
n_m = min(len(y_te_inv), len(mia_pred))
plot_forecast(axes[1, 1], 'МГУА — MIA (нелинейный)',
              y_te_inv[:n_m], mia_pred[:n_m],
              color='mediumpurple')

plt.tight_layout()
plt.savefig('forecasts.png', dpi=150, bbox_inches='tight')
plt.show()

# ── Ячейка 12: Итоговое сравнение ─────────────────────────────
print("\n" + "="*60)
print("ИТОГОВОЕ СРАВНЕНИЕ МОДЕЛЕЙ")
print("="*60)

results = pd.DataFrame({
    'Модель': ['SARIMA', 'Символьная регрессия',
               'МГУА COMBI', 'МГУА MIA'],
    'MAE':   [mae_arima,  mae_sr,  mae_combi,  mae_mia],
    'RMSE':  [rmse_arima, rmse_sr, rmse_combi, rmse_mia],
    'MAPE%': [mape_arima, mape_sr, mape_combi, mape_mia],
})
results = results.sort_values('MAPE%').reset_index(drop=True)
print(results.to_string(index=False))

# График сравнения
fig, ax = plt.subplots(figsize=(9, 4))
colors = ['#4C72B0', '#DD8452', '#55A868', '#C44E52']
bars = ax.barh(results['Модель'], results['MAPE%'],
               color=colors, edgecolor='black', height=0.5)
ax.set_xlabel('MAPE, %')
ax.set_title('Сравнение качества прогнозов (MAPE)',
             fontweight='bold')
for bar, val in zip(bars, results['MAPE%']):
    ax.text(val + 0.1, bar.get_y() + bar.get_height() / 2,
            f'{val:.2f}%', va='center')
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()